### ISSUE TITLE
Impliment server status for game server cards?

### ISSUE THREAD

**Issue by PerplexativeKhat** [Egeeio/egeeio-website#86]
Perhaps with the hooks in the game servers for Androgee you could add a "Sever status" area in the server cards!

**Comment by StripedMonkey** [comment]
This might be a good idea for a separate page that is essentially a table
of all the servers we have ever run in a grid along with their status and
notes about them (Eg. Modded server has been suspended due to inactivity or
similar) Having an uptime% would be a nice little feature to advertise
server stability.

We admins already have a spreadsheet that sorta reflects this idea (albeit
with information like ssh ports for individual servers) I might try and
make this a project to implement although I'm not sure how uptime tracking
would be handled. I give a 40% chance I will actually have the time to try
and do something like this, I'm sure the documentation is out there
however.

On Sat, Jun 10, 2017 at 10:55 PM, PerplexativeKhat <notifications@github.com

**Comment by gogosrcool** [comment]
Similar to #90, closing issue and referencing.
